package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Tests'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Tests")) {
    params {
        add {
            password("env.123", "credentialsJSON:038b874d-0e2e-47ec-b117-fe8d77c72944")
        }
    }
}
