package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        add {
            feature {
                type = "Invitation"
                id = "PROJECT_EXT_4625"
                param("createdByUserId", "4330")
                param("invitationType", "joinProjectInvitation")
                param("roleId", "PROJECT_DEPLOYER")
                param("secure:token", "credentialsJSON:ce90bdb5-315b-4422-b6d6-6ac37c872974")
                param("name", "Join project")
                param("welcomeText", "Viacheslav Suvorov invites you to join the AI Development Kit project")
                param("disabled", "false")
                param("groupKey", "AI_DEVELOPMENT_KIT_ADMINISTRATORS")
                param("multi", "true")
            }
        }
    }
}
