package ai.dev.kit.providers.mlflow

import ai.dev.kit.core.fluent.FluentSpanAttributes
import ai.dev.kit.core.fluent.dataclasses.RunStatus
import ai.dev.kit.core.fluent.dataclasses.TraceInfo
import ai.dev.kit.core.fluent.processor.TracingFlowProcessor
import ai.dev.kit.eval.utils.*
import ai.dev.kit.providers.mlflow.dataclasses.*
import io.opentelemetry.api.trace.Span
import io.opentelemetry.api.trace.Tracer
import io.opentelemetry.context.Scope
import io.opentelemetry.extension.kotlin.asContextElement
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withContext
import kotlinx.serialization.json.Json
import org.junit.jupiter.api.*
import java.util.stream.Stream

/**
 * A base abstract class for conducting evaluation tests on AI functionality.
 * The class manages multiple test runs within an experiment and provides mechanisms for evaluating
 * AI outputs against ground-truth data while logging the results into MLflow.
 *
 * @param AIInputT The type of input provided to the AI system under test.
 * @param GroundTruthT The type of ground-truth data used for evaluation.
 * @param AIOutputT The type of output generated by the AI system.
 * @param EvalResultT The type of evaluation result representing scores or metrics assigned for a test.
 * @param experimentName The name of the experiment in MLflow where the test results will be logged.
 * @param runNamePrefix A prefix used for naming the runs within the experiment.
 * @param numberOfRuns The number of test runs to execute during the evaluation process.
 * @param tags A list of tags associated with each run, used for metadata purposes. The size of this list must match `numberOfRuns`.
 */
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
abstract class BaseEvaluationTest<
        AIInputT : AIInput,
        GroundTruthT : GroundTruth,
        AIOutputT : AIOutput,
        EvalResultT : EvalResult
        >(
    private val experimentName: String = "Evaluation test",
    private val runNamePrefix: String = createRandomRunNameAdjectiveNounNumber(),
    private val numberOfRuns: Int = 1,
    private val tags: List<RunTag> = listOf(),
) {
    init {
        require(tags.isEmpty() || tags.size == numberOfRuns) { "The number of tags must match the number of runs" }
    }

    private lateinit var experimentId: String
    private val runResults = mutableListOf<RunResults<AIInputT, GroundTruthT, AIOutputT, EvalResultT>>()

    @BeforeAll
    fun beforeAll() {
        println("🔄 Setting up before all tests")

        TracingFlowProcessor.setupTracing(MlflowDiContainer.di)

        experimentId = getExperimentByName(KotlinMlflowClient, experimentName)?.experimentId
            ?: createExperiment(KotlinMlflowClient, experimentName)
                    ?: throw IllegalStateException("Failed to create or retrieve experiment '$experimentName' at ${KotlinMlflowClient.ML_FLOW_URL}")

        KotlinMlflowClient.currentExperimentId = experimentId

        (1..numberOfRuns).map { runNum ->
            runBlocking {
                val runId = createRun(
                    KotlinMlflowClient,
                    runNamePrefix + if (numberOfRuns > 1) "/subrun-$runNum" else "",
                    experimentId
                )?.runId.toString()

                KotlinMlflowClient.currentRunId = runId
                runResults.add(RunResults(mutableListOf(), runId, RunStatus.FINISHED))
            }
        }
    }

    @AfterAll
    fun afterAll() {
        println("📊 Logging evaluation results")

        runResults.forEachIndexed { runIndex, runResult ->
            val (testResults, runId, runStatus) = runResult
            try {
                runBlocking {
                    if (tags.isNotEmpty())
                        setTag(
                            runId,
                            "mlflow.runColor",
                            tags[runIndex].color,
                        )
                }
                uploadResultsTableAsArtifact(runId, testResults)
                logAverageScore(runId, testResults.map { it.evalResult })
            } catch (_: Exception) {
                runResults[runIndex].finalStatus = RunStatus.FAILED
            } finally {
                runBlocking { updateRun(runId, runStatus) }
            }
        }
    }

    @TestFactory
    fun Runs(): Stream<DynamicContainer> = runResults.mapIndexed { runNum, runResult ->
        DynamicContainer.dynamicContainer(
            "Run ${if (runResults.size > 1) runNum + 1 else ""}",
            testCases.mapIndexed { dataPointIndex, testCase ->
                val (dataPointSpan, dataPointScope) =
                    createDataPointSpan(dataPointIndex, TracingFlowProcessor.tracer, runResult.runId, testCase)
                val output = runBlocking {
                    withContext(dataPointSpan.asContextElement()) {
                        generator.generate(testCase.input)
                    }
                }
                val testCaseName = testCase.name
                DynamicTest.dynamicTest(testCaseName) {
                    dataPointSpan.makeCurrent()
                    try {
                        executeSingleTest(testCaseName, testCase, runNum, runResult.runId, output)
                    } finally {
                        dataPointSpan.end()
                        dataPointScope.close()
                    }
                }
            }
        )
    }.stream()

    private fun createDataPointSpan(
        dataPointIndex: Int,
        tracer: Tracer,
        runId: String,
        testCase: TestCase<AIInputT, GroundTruthT>
    ): Pair<Span, Scope> {
        val tracedRunName = "Data Point ${dataPointIndex + 1}"
        val dataPointSpan = tracer.spanBuilder(tracedRunName).setNoParent().also {
            runBlocking {
                val tracePostRequest = createTracePostRequest(
                    experimentId = experimentId,
                    runId = runId,
                    traceCreationPath = "No path for root test",
                    traceName = tracedRunName
                )

                val jsonTraceInfo = Json.encodeToString(TraceInfo.serializer(), createTrace(tracePostRequest))
                it.setAttribute(FluentSpanAttributes.TRACE_CREATION_INFO.key, jsonTraceInfo)
                it.setAttribute(
                    FluentSpanAttributes.SPAN_INPUTS.key,
                    "{\"Data Point\": \"${testCase.input}\"}"
                )
            }
        }.startSpan()
        val dataPointScope = dataPointSpan.makeCurrent()
        return dataPointSpan to dataPointScope
    }

    private fun executeSingleTest(
        testCaseName: String,
        testCase: TestCase<AIInputT, GroundTruthT>,
        runNum: Int,
        runId: String,
        output: AIOutputT
    ) {
        val result = try {
            evaluator.evaluate(testCase.groundTruth, output)
        } catch (e: Throwable) {
            val message = "❌ Test Failed: $testCaseName | Case: $testCase | Reason: Evaluator has thrown ${e.message}"
            logTest(message, runId)
            fail(message)
        }
        runResults[runNum].testResults.add(
            TestResult<AIInputT, GroundTruthT, AIOutputT, EvalResultT>(
                testCase,
                output,
                result
            )
        )

        if (result.hasJunitTestSucceeded) {
            logTest(
                message = "✅ Test Passed: $testCaseName | Case: $testCase | Result: $result",
                runId = runId
            )
        } else {
            val message = "❌ Test failed: $testCaseName | Case: $testCase | Result: $result"
            logTest(message, runId)
            fail(message)
        }
    }

    private fun logTest(message: String, runId: String) {
        println(message)
        println("🔗 View results at ${KotlinMlflowClient.ML_FLOW_URL}/#/experiments/$experimentId/runs/$runId")
    }

    private fun uploadResultsTableAsArtifact(
        runId: String,
        testResults: List<TestResult<AIInputT, GroundTruthT, AIOutputT, EvalResultT>>
    ) {
        val loggedRun = runBlocking { getRun(runId) }
        val artifactPath = "${loggedRun.info.experimentId}/${runId}/artifacts/eval_results_table.json"

        val table = testResults.toTable() ?: return
        uploadArtifact(artifactPath, table.dumpForMLFlow())

        runBlocking {
            setTag(
                runId,
                "mlflow.loggedArtifacts",
                "[{\"path\": \"eval_results_table.json\", \"type\": \"table\"}]"
            )
        }
    }

    private fun logAverageScore(runId: String, evalResults: List<EvalResultT>) {
        val aggregateScores = evaluator.aggregateResults(evalResults)
        for (agg in aggregateScores) {
            logMetric(KotlinMlflowClient, runId, agg.scoreName, agg.score)
        }
        if (aggregateScores.isNotEmpty()) {
            println("📈 Results logged to MLFlow for Run ID: $runId")
        }
    }

    abstract val testCases: List<TestCase<AIInputT, GroundTruthT>>
    abstract val generator: Generator<AIInputT, AIOutputT>
    abstract val evaluator: Evaluator<GroundTruthT, AIOutputT, EvalResultT>
}

private data class RunResults<
        AIInputT : AIInput,
        GroundTruthT : GroundTruth,
        AIOutputT : AIOutput,
        EvalResultT : EvalResult
        >(
    val testResults: MutableList<TestResult<AIInputT, GroundTruthT, AIOutputT, EvalResultT>>,
    val runId: String,
    var finalStatus: RunStatus,
)
