import org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17

plugins {
    kotlin("multiplatform")
    alias(libs.plugins.kotlin.serialization)
    id("ai.dev.kit.space.publishing")
    id("ai.dev.kit.trace")
    id("ai.kotlin.dokka")
}

kotlin {
    jvmToolchain(17)

    jvm {
        compilerOptions.jvmTarget = JVM_17
    }

    sourceSets {
        commonMain {
            dependencies {
                implementation(libs.kotlinx.serialization.core)
                implementation(libs.kotlinx.serialization.json)
                implementation(libs.ktor.client)
            }
        }

        jvmMain {
            dependencies {
                implementation(libs.okhttp)
                implementation(libs.ktor.client)
                implementation(libs.ktor.client.cio)
                implementation(libs.ktor.serialization.json)
                implementation(libs.ktor.client.negotiation)
                implementation(libs.kotlin.reflect)
                implementation(libs.opentelemetry.sdk)
                implementation(libs.opentelemetry.kotlin)
                implementation(libs.opentelemetry.exporter.otlp)
                implementation(libs.opentelemetry.exporter.otlp.common)
                implementation(libs.opentelemetry.exporter.logging)
                implementation(libs.opentelemetry.exporter.logging.otlp)
                implementation(libs.opentelemetry.semconv.incubating)
                implementation(libs.kotlinx.coroutines)
                implementation(libs.kotlin.logging)
                implementation(libs.apache.mime4j.core)
                implementation(libs.apache.mime4j)
            }
        }

        jvmTest {
            dependencies {
                implementation(libs.kotlin.test)
                implementation(libs.junit.params)
                implementation(libs.kotlinx.coroutines.test)
                implementation(libs.okhttp.mockwebserver)
                implementation(libs.opentelemetry.sdk.testing)
                implementation(libs.logback.classic)
                implementation(project(":tracing:test-utils"))
            }
        }
    }
}

val generatedBuildConfigDir = layout.buildDirectory.dir("generated/commonMain")
val version = providers.gradleProperty("VERSION").orNull
    ?: error("Missing VERSION property")

tasks.register("generateBuildConfig") {
    val outputDir = generatedBuildConfigDir.get()
    outputs.dir(generatedBuildConfigDir)

    doLast {
        val file = outputDir.file("ai/dev/kit/config/BuildConfig.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            // Generated by Gradle task 'generateBuildConfig'.
            // Do not edit manually! Changes will be overwritten.
            
            package ai.dev.kit.config
            
            object BuildConfig {
                const val VERSION: String = "$version"
            }
            """.trimIndent()
        )
    }
}

kotlin {
    sourceSets {
        val commonMain by getting {
            kotlin.srcDir(layout.buildDirectory.dir("generated/commonMain"))
        }
    }
}


tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    compilerOptions {
        freeCompilerArgs.addAll(
            "-java-parameters", "-Xexpect-actual-classes"
        )
    }
    dependsOn("generateBuildConfig")
}
