/*
 * Copyright © 2026 JetBrains s.r.o. and contributors.
 * Use of this source code is governed by the Apache 2.0 license.
 */

import org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17

plugins {
    kotlin("multiplatform")
    alias(libs.plugins.kotlin.serialization)
    id("ai.jetbrains.tracy.published-artifact")
    id("org.jetbrains.ai.tracy")
    id("ai.kotlin.dokka")
}

kotlin {
    jvmToolchain(17)

    jvm {
        compilerOptions.jvmTarget = JVM_17
    }

    sourceSets {
        val commonMain by getting {
            kotlin.srcDir(layout.buildDirectory.dir("generated/commonMain"))
        }

        jvmMain {
            dependencies {
                implementation(libs.okhttp)
                implementation(libs.ktor.client)
                implementation(libs.ktor.client.cio)
                implementation(libs.ktor.serialization.json)
                implementation(libs.ktor.client.negotiation)
                implementation(libs.kotlin.reflect)
                api(libs.opentelemetry.sdk)
                implementation(libs.opentelemetry.kotlin)
                implementation(libs.opentelemetry.exporter.otlp)
                implementation(libs.opentelemetry.exporter.otlp.common)
                implementation(libs.opentelemetry.exporter.logging)
                implementation(libs.opentelemetry.exporter.logging.otlp)
                implementation(libs.opentelemetry.semconv.incubating)
                implementation(libs.kotlinx.coroutines)
                implementation(libs.kotlin.logging)
                implementation(libs.apache.mime4j.core)
                implementation(libs.apache.mime4j)
            }
        }

        jvmTest {
            dependencies {
                implementation(libs.kotlin.test)
                implementation(libs.junit.params)
                implementation(libs.kotlinx.coroutines.test)
                implementation(libs.okhttp.mockwebserver)
                implementation(libs.opentelemetry.sdk.testing)
                implementation(libs.logback.classic)
                implementation(project(":tracing:test-utils"))
            }
        }
    }
}

val generatedBuildConfigDir = layout.buildDirectory.dir("generated/commonMain")
val version = providers.gradleProperty("VERSION").orNull
    ?: error("Missing VERSION property")

val generateBuildConfig by tasks.registering {
    val outputDir = generatedBuildConfigDir.get()
    outputs.dir(generatedBuildConfigDir)

    doLast {
        val file = outputDir.file("ai/jetbrains/tracy/config/BuildConfig.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            // Generated by Gradle task 'generateBuildConfig'.
            // Do not edit manually! Changes will be overwritten.
            
            package ai.jetbrains.tracy.config
            
            object BuildConfig {
                const val VERSION: String = "$version"
            }
            """.trimIndent()
        )
    }
}

tasks.named("dokkaGeneratePublicationHtml") {
    dependsOn(generateBuildConfig)
}
tasks.named("dokkaGeneratePublicationJavadoc") {
    dependsOn(generateBuildConfig)
}
tasks.named("dokkaGenerateModuleHtml") {
    dependsOn(generateBuildConfig)
}
tasks.named("dokkaGenerateModuleJavadoc") {
    dependsOn(generateBuildConfig)
}

tasks.named("jvmSourcesJar") {
    dependsOn(generateBuildConfig)
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
    dependsOn(generateBuildConfig)
    compilerOptions {
        freeCompilerArgs.addAll("-java-parameters", "-Xexpect-actual-classes")
    }
}


publishing {
    publications.withType<MavenPublication>().configureEach {
        artifactId = "tracy-$artifactId"
        pom {
            name.set(artifactId)
            description.set("Core tracing module of the Tracy library.")
        }
    }
}

