site_name: AI Development Kit
#site_url: [link-to-hosted-docs]
# TODO: add site_url, favicon, style.css (for details, see PR description: https://github.com/JetBrains/ai-dev-kit/pull/95)
nav:
  - Documentation:
      - Welcome to MkDocs: index.md
      - Overview: overview.md
      - Tracing API: tracing-api.md
      - Supported Backends: supported-backends.md
#      - Key concepts: key-concepts.md
#      - Getting started:
#          - Single-run agents: single-run-agents.md
#          - Functional agents: functional-agents.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - admonition
  - attr_list
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - macros

theme:
  name: material
  custom_dir: overrides
  favicon: img/favicon.ico
  logo: img/favicon.ico
  features:
    - content.code.copy
    - content.action.edit
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
  color_mode: light
  nav_style: light
  user_color_mode_toggle: true
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
      primary: black
      accent: blue
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
      primary: black
      accent: blue

extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/JetBrains/ai-dev-kit
repo_name: "AI Dev Kit on GitHub"
edit_uri: edit/develop/docs/docs/
copyright: Copyright © 2000-2025 JetBrains s.r.o.

#extra:
#  social:
#   TODO: Add a similar link as in Koog (e.g., https://docs.koog.ai/koog-slack-channel) and name
#    - icon: fontawesome/brands/slack
#      link: ?
#      name: ?